### ISSUE TITLE
Error when trying to delete invalid payment definition

### ISSUE THREAD

**Issue by rsomoza** [paypal/PayPal-PHP-SDK#1112]
### General information
* SDK/Library version: PHP-SDK 1.13.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 71c4bf8fb4463
* Language, language version, and OS: PHP 5.4.45 running under Apache

### Issue description
I created by mistake a test billing plan with "frequency_interval": "33" (i.e., greater than annual frequency). The plan was created CORRECTLY and can be retrieved also without any problem.
However, when I tried to DELETE the billing plan, I got a validation error "frequency more than year is not supported" (see Logs below). 

Creation and deletion of valid payment plans occur without a hitch.

There seems to be an error in the API, where the validation about the validity of the billing plan is performed when you try to **delete** it, and NOT when you try to **create** it.

### ERROR Message:
Fatal error: Uncaught exception 'PayPal\Exception\PayPalConnectionException' with message 'Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-plans/P-67774891RK647024ATYEHIRI.' in /home/u-2.co/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:202 Stack trace: #0 /home/u-2.co/vendor/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php(78): PayPal\Core\PayPalHttpConnection->execute('[{"op":"replace...') #1 /home/u-2.co/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php(104): PayPal\Transport\PayPalRestCall->execute(Array, '/v1/payments/bi...', 'PATCH', '[{"op":"replace...', NULL) #2 /home/u-2.co/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Plan.php(388): PayPal\Common\PayPalResourceModel::executeCall('/v1/payments/bi...', 'PATCH', '[{"op":"replace...', NULL, NULL, NULL) #3 /home/u-2.co/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Plan.php(411): PayPal\Api\Plan->update(Object(PayPal\Api\PatchRequest), NULL, NULL) in /home/u-2.co/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php on line 202

### LOGS
[26-05-2018 15:07:52] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-plans/P-67774891RK647024ATYEHIRI. {"name":"VALIDATION_ERROR","details":[{"field":"payment_definitions[0].frequency_interval","issue":"frequency more than year is not supported"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/payments.billing-plans#errors","debug_id":"71c4bf8fb4463"}

================================================================================================================================

[26-05-2018 15:30:30] PayPal\Core\PayPalHttpConnection : INFO: PATCH https://api.sandbox.paypal.com/v1/payments/billing-plans/P-67774891RK647024ATYEHIRI
[26-05-2018 15:30:33] PayPal\Core\PayPalHttpConnection : DEBUG: Request Headers 	: PATCH /v1/payments/billing-plans/P-67774891RK647024ATYEHIRI HTTP/1.1, Host: api.sandbox.paypal.com, Accept: */*, Content-Type: application/json, User-Agent: PayPalSDK/PayPal-PHP-SDK 1.13.0 (platform-ver=5.4.45; bit=64; os=Linux_3.10.0-693.17.1.2.ELK.el6.x86_64; machine=x86_64; crypto-lib-ver=1.0.1e-fips; curl=7.19.7), Authorization: Bearer A21AAGDV8zYrtScueHKa_STc6nv8YD68gX6ReGqxbgP9Aj22hCOAa99uEAZVrhSFSHtzXDWO18axG2zUslBK4r5TyKZFhOF2g, Content-Length: 57, , 
[26-05-2018 15:30:33] PayPal\Core\PayPalHttpConnection : DEBUG: Request Data		: [{"op":"replace","path":"/","value":{"state":"DELETED"}}]
--------------------------------------------------------------------------------------------------------------------------------

[26-05-2018 15:30:33] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 400
[26-05-2018 15:30:33] PayPal\Core\PayPalHttpConnection : DEBUG: Response Headers	: Date: Sat, 26 May 2018 20:30:30 GMT, Server: Apache, paypal-debug-id: 969a25ca874e6, Content-Language: *, Connection: close, HTTP_X_PP_AZ_LOCATOR: sandbox.slc, Paypal-Debug-Id: 969a25ca874e6, Set-Cookie: X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT, Vary: Authorization, Content-Length: 303, Content-Type: application/json, 
[26-05-2018 15:30:33] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-plans/P-67774891RK647024ATYEHIRI. {"name":"VALIDATION_ERROR","details":[{"field":"payment_definitions[0].frequency_interval","issue":"frequency more than year is not supported"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/payments.billing-plans#errors","debug_id":"969a25ca874e6"}
[26-05-2018 15:30:33] PayPal\Core\PayPalHttpConnection : DEBUG: 

================================================================================================================================

### Offending text billing plan data (retrieved from Sandbox environment)
{ "id": "P-67774891RK647024ATYEHIRI", "state": "CREATED", "name": "prueba", "description": "prueba", "type": "INFINITE", "create_time": "2018-05-26T19:59:04.261Z", "update_time": "2018-05-26T19:59:04.261Z", "links": [ { "href": "https://api.sandbox.paypal.com/v1/payments/billing-plans/P-67774891RK647024ATYEHIRI", "rel": "self", "method": "GET" } ] }
{ "id": "P-67774891RK647024ATYEHIRI", "state": "CREATED", "name": "prueba", "description": "prueba", "type": "INFINITE", "payment_definitions": [ { "id": "PD-896302683K870345GTYEHIRI", "name": "prueba", "type": "REGULAR", "frequency": "Month", "amount": { "currency": "EUR", "value": "333" }, "cycles": "0", "charge_models": [], "frequency_interval": "33" } ], "merchant_preferences": { "setup_fee": { "currency": "EUR", "value": "0" }, "max_fail_attempts": "0", "return_url": "http://dragonkin.global/Responses/subscriptioncallback.php?success=true", "cancel_url": "http://dragonkin.global/Responses/subscriptioncallback.php?success=false", "auto_bill_amount": "YES", "initial_fail_amount_action": "CONTINUE" }, "create_time": "2018-05-26T19:59:04.261Z", "update_time": "2018-05-26T19:59:04.261Z", "links": [ { "href": "https://api.sandbox.paypal.com/v1/payments/billing-plans/P-67774891RK647024ATYEHIRI", "rel": "self", "method": "GET" } ] }

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity.
