### ISSUE TITLE
Error in submitting payment

### ISSUE THREAD

**Issue by pryxen12** [paypal/PayPal-PHP-SDK#1120]
```
28 exception 'PayPal\Exception\PayPalConnectionException' with message 'Resolving timed out after 10733 milliseconds' in C:\xampp\htdocs\test\vendor\paypal\rest-api-sdk-php\lib\PayPal\Core\PayPalHttpConnection.php:181
Stack trace:
#0 C:\xampp\htdocs\test\vendor\paypal\rest-api-sdk-php\lib\PayPal\Auth\OAuthTokenCredential.php(246): PayPal\Core\PayPalHttpConnection->execute('grant_type=clie...')
#1 C:\xampp\htdocs\test\vendor\paypal\rest-api-sdk-php\lib\PayPal\Auth\OAuthTokenCredential.php(271): PayPal\Auth\OAuthTokenCredential->getToken(Array, 'AU1GMEhkzu6kYlr...', 'ELlJUgpAqOe5HvS...', 'grant_type=clie...')
#2 C:\xampp\htdocs\test\vendor\paypal\rest-api-sdk-php\lib\PayPal\Auth\OAuthTokenCredential.php(210): PayPal\Auth\OAuthTokenCredential->generateAccessToken(Array, NULL)
#3 C:\xampp\htdocs\test\vendor\paypal\rest-api-sdk-php\lib\PayPal\Auth\OAuthTokenCredential.php(160): PayPal\Auth\OAuthTokenCredential->updateAccessToken(Array)
#4 C:\xampp\htdocs\test\vendor\paypal\rest-api-sdk-php\lib\PayPal\Handler\RestHandler.php(82): PayPal\Auth\OAuthTokenCredential->getAccessToken(Array)
#5 C:\xampp\htdocs\test\vendor\paypal\rest-api-sdk-php\lib\PayPal\Transport\PayPalRestCall.php(75): PayPal\Handler\RestHandler->handle(Object(PayPal\Core\PayPalHttpConfig), '{"intent":"sale...', Array)
#6 C:\xampp\htdocs\test\vendor\paypal\rest-api-sdk-php\lib\PayPal\Common\PayPalResourceModel.php(104): PayPal\Transport\PayPalRestCall->execute(Array, '/v1/payments/pa...', 'POST', '{"intent":"sale...', NULL)
#7 C:\xampp\htdocs\test\vendor\paypal\rest-api-sdk-php\lib\PayPal\Api\Payment.php(577): PayPal\Common\PayPalResourceModel::executeCall('/v1/payments/pa...', 'POST', '{"intent":"sale...', NULL, Object(PayPal\Rest\ApiContext), NULL)
#8 C:\xampp\htdocs\test\index.php(46): PayPal\Api\Payment->create(Object(PayPal\Rest\ApiContext))
#9 {main}
```

I always got a error like whenever I test my code locally. I don't know where is the problem and on my account in a hosting site the Item class always gives me an error

by the way this is the code I test which I got in [paypal](https://developer.paypal.com/docs/api/quickstart/payments/)

```
<?php 

require 'vendor/autoload.php';

$apiContext = new \PayPal\Rest\ApiContext(
  new \PayPal\Auth\OAuthTokenCredential(
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  )
);

use PayPal\Api\Amount;
use PayPal\Api\Details;
use PayPal\Api\Item;
use PayPal\Api\ItemList;
use PayPal\Api\Payer;
use PayPal\Api\Payment;
use PayPal\Api\RedirectUrls;
use PayPal\Api\Transaction;

$payer = new Payer();
$payer->setPaymentMethod("paypal");


$redirectUrls = new RedirectUrls();
$redirectUrls->setReturnUrl('http://localhost:8080/test/process.php')
  ->setCancelUrl('http://localhost:8080/test/cancel.php');


$amount = new Amount();
$amount->setCurrency("USD")
  ->setTotal(10);

$transaction = new Transaction();
$transaction->setAmount($amount)
  ->setDescription("Payment description");


$payment = new Payment();
$payment->setIntent('sale')
  ->setPayer($payer)
  ->setRedirectUrls($redirectUrls)
  ->setTransactions(array($transaction));

try {
  $payment->create($apiContext);


  $approvalUrl = $payment->getApprovalLink();

} catch (PayPal\Exception\PayPalConnectionException $ex) {
  echo $ex->getCode();
  echo $ex->getData();
  die($ex);
} catch (Exception $ex) {
  die($ex);
}
```

**Comment by trainerbill** [comment]
Its timing out so either you have really slow internet or a firewall blocking you somewhere.
