### ISSUE TITLE
MALFORMED_REQUEST for Agreement

### ISSUE THREAD

**Issue by RoguePoma** [paypal/PayPal-PHP-SDK#1212]
### General information

SDK/Library version: 4.8.35
Environment: Sandbox
'PayPal-Debug-ID` values: 741225f51ee34

### Issue description
I am attempting to create a subscription payment to my website. Here is the current code I am using to create the agreement and attempt to allow the payer to get redirected to the agreement url.

`$createdPlan = new Plan();

    $createdPlan->setName($product_name)
        ->setDescription($product_description)
        ->setType('fixed');
    $paymentDefinition = new PaymentDefinition();

    $paymentDefinition->setName('Regular Payments')
        ->setType('REGULAR')
        ->setFrequency($payment_frequency)
        ->setFrequencyInterval($payment_intervals)
        ->setCycles($payment_cycles)
        ->setAmount(new Currency(array('value' => $product_price, 'currency' => $currency)));

    $chargeModel = new ChargeModel();
    $chargeModel->setType('SHIPPING')
        ->setAmount(new Currency(array('value' => $setup_fee, 'currency' => $currency)));
    $paymentDefinition->setChargeModels(array($chargeModel));
    $merchantPreferences = new MerchantPreferences();

    $merchantPreferences->setReturnUrl("https://$baseUrl/order/scripts/paypal/ExecuteAgreement.php?success=true&productId=$product_id&checkout_id=$checkout_id")
        ->setCancelUrl("https://$baseUrl/order/scripts/paypal/ExecuteAgreement.php?success=false&productId=$product_id")
        ->setAutoBillAmount("yes")
        ->setInitialFailAmountAction("CONTINUE")
        ->setMaxFailAttempts("0")
        ->setSetupFee(new Currency(array('value' => $setup_fee, 'currency' => $currency)));

    $createdPlan->setPaymentDefinitions(array($paymentDefinition));
    $createdPlan->setMerchantPreferences($merchantPreferences);

    try {
        $output = $createdPlan->create($apiContext);

        $dt = date("Y-m-d H:i:s");
        $currentDateTime = new DateTime($dt);
        $currentDateTime->add(new DateInterval('PT1H'));

        $agreement = new Agreement();
        $agreement->setName($product_name)
            ->setDescription($product_description)
            ->setStartDate($currentDateTime);

        $plan_id = new Plan();
        $plan_id->setId($createdPlan->getId());
        $agreement->setPlan($plan_id);

        $payer = new Payer();
        $payer->setPaymentMethod('paypal');
        $agreement->setPayer($payer);
        

        $request = clone $agreement;

        try {
            $agreement = $agreement->create($apiContext);
            $approvalUrl = $agreement->getApprovalLink();

        } catch (PayPal\Exception\PayPalConnectionException $ex) {
            echo $ex->getCode(); // Prints the Error Code
            echo $ex->getData(); // Prints the detailed error message
            die($ex);
        } catch (Exception $ex) {
            die($ex);
        }
        header("Location: " . $approvalUrl);
        return $agreement;

    } catch (PayPal\Exception\PayPalConnectionException $ex) {
        echo $ex->getCode(); // Prints the Error Code
        echo $ex->getData(); // Prints the detailed error message
        die($ex);
    } catch (Exception $ex) {
        die($ex);
    }
}`

But I get the following error

`400{"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST","debug_id":"741225f51ee34"}exception 'PayPal\Exception\PayPalConnectionException' with message 'Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/billing-agreements/.' in /data/www/default/my_site/scripts/vendors/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:216 Stack trace: #0 /data/www/default/my_site/scripts/vendors/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php(82): PayPal\Core\PayPalHttpConnection->execute('{"name":"Monthl...') #1 /data/www/default/my_site/scripts/vendors/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php(110): PayPal\Transport\PayPalRestCall->execute(Array, '/v1/payments/bi...', 'POST', '{"name":"Monthl...', NULL) #2 /data/www/default/my_site/scripts/vendors/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Api/Agreement.php(393): PayPal\Common\PayPalResourceModel::executeCall('/v1/payments/bi...', 'POST', '{"name":"Monthl...', NULL, Object(PayPal\Rest\ApiContext), NULL) #3 /data/www/default/my_site/order/scripts/paypal/paypal-functions.php(143): PayPal\Api\Agreement->create(Object(PayPal\Rest\ApiContext)) #4 /data/www/default/my_site/order/scripts/payment.php(33): createRecurringPayment('7', 'www.mysite.co...', Object(PayPal\Rest\ApiContext), '2', 'Monthly Members...', 'Gain access to ...', '20.00', 'Month', '1') #5 {main}`

Any help would be gratefully appreciated as ive been trying to get subscriptions added to my site for a week now with no luck.

**Comment by RoguePoma** [comment]
After some tweaking it was the date I was setting
