### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by StylishSingh** [paypal/PayPal-PHP-SDK#1214]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

Fatal error: Uncaught PayPal\Exception\PayPalConnectionException: Got Http response code 401 when accessing https://api.sandbox.paypal.com/v1/oauth2/token. in /home/httpgraceappco/public_html/booking/payment/libraries/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:202 Stack trace: #0 /home/httpgraceappco/public_html/booking/payment/libraries/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(246): PayPal\Core\PayPalHttpConnection->execute('grant_type=clie...') #1 /home/httpgraceappco/public_html/booking/payment/libraries/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(271): PayPal\Auth\OAuthTokenCredential->getToken(Array, 'Aa9kKDXNL0iHcB9...', 'EN9oeBp-ANoYr_8...', 'grant_type=clie...') #2 /home/httpgraceappco/public_html/booking/payment/libraries/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(210): PayPal\Auth\OAuthTokenCredential->generateAccessToken(Array, NULL) #3 /home/httpgraceappco/public_ in /home/httpgraceappco/public_html/booking/payment/libraries/PayPal-PHP-SDK/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php on line 202

**Comment by prakash-gangadharan** [comment]
Hi @StylishSingh,  can you add the `PayPal-Debug-ID` of the latest instance of this issue ?
