### ISSUE TITLE
Uncaught exception 'ReflectionException' with message 'Method PayPal\\Api\\Authorization::getProcessorResponse() does not exist

### ISSUE THREAD

**Issue by sumityadav** [paypal/PayPal-PHP-SDK#397]
From this Monday we have started receiving the following error message:

```
[Wed Sep 16 20:05:08.287265 2015][:error] PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Method PayPal\\Api\\Authorization::getProcessorResponse() does not exist' in paypal/sdk-core-php/lib/PayPal/Common/PPReflectionUtil.php:60
Stack trace:
#0 paypal/sdk-core-php/lib/PayPal/Common/PPReflectionUtil.php(60): ReflectionMethod->__construct('PayPal\\Api\\Auth...', 'getProcessorRes...')
#1 paypal/sdk-core-php/lib/PayPal/Common/PPReflectionUtil.php(24): PayPal\\Common\\PPReflectionUtil::propertyAnnotations('PayPal\\Api\\Auth...', 'processor_respo...')
#2 paypal/sdk-core-php/lib/PayPal/Common/PPModel.php(48): PayPal\\Common\\PPReflectionUtil::getPropertyClass('PayPal\\Api\\Auth...', 'processor_respo...')
#3 paypal/sdk-core-php/lib/PayPal/Common/PPModel.php(52): PayPal\\Common\\PPModel->fromArray(Array)
#4 paypal/sdk-core-php/lib/PayPal/Common/PPReflectionUtil.php on line 60
```

**Comment by jaypatel512** [comment]
Hey @sumityadav ! 

It looks like you have few missing properties. You should be able to resolve the issue by simply updating to latest version. Also, I see that you are using 0.* version of our SDK. I would highly recommend using 1.*. There are few [minor breaking changes](https://github.com/paypal/PayPal-PHP-SDK/wiki/Breaking-Changes---1.0.0), but it has much more features, bug fixes, and optimizations.
