### ISSUE TITLE
Handshake Failure

### ISSUE THREAD

**Issue by tekmosis** [paypal/PayPal-PHP-SDK#483]
While following the example for PayPal Express found here
http://paypal.github.io/PayPal-PHP-SDK/sample/doc/payments/CreatePaymentUsingPayPal.html

On my developer.paypal.com applications I've taken the ClientId and ClientSecret information from the Sandbox section. Status is Enabled.
App Settings are as follows; Checked off, Accept Payments, Invoicing, Payouts. Unchecked, PayPal Here and Login In with PayPal. I also have no webhooks added.

I have my ApiContext setup as follows;
```
$oAuthTokenCredential = new PayPal\Auth\OAuthTokenCredential($clientId, $clientSecret);
$apiContext = new ApiContext($oAuthTokenCredential);
$apiContext->setConfig(array(
    'mode' => 'sandbox'
));
```

I'm running into nothing but problems. I cannot get the approval link. Calling `$payment->create($apiContext);` throws the following PayPalConnectionException

```
exception 'PayPal\Exception\PayPalConnectionException' with message 'error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure' in /PayPal/lib/PayPal/Core/PayPalHttpConnection.php:137
Stack trace:
#0 /PayPal/lib/PayPal/Auth/OAuthTokenCredential.php(249): PayPal\Core\PayPalHttpConnection->execute('grant_type=clie...')
#1 /PayPal/lib/PayPal/Auth/OAuthTokenCredential.php(274): PayPal\Auth\OAuthTokenCredential->getToken(Array, 'A........', 'E........', 'grant_type=clie...')
#2 /PayPal/lib/PayPal/Auth/OAuthTokenCredential.php(218): PayPal\Auth\OAuthTokenCredential->generateAccessToken(Array, NULL)
#3 /PayPal/lib/PayPal/Auth/OAuthTokenCredential.php(168): PayPal\Auth\OAuthTokenCredential->updateAccessToken(Array)
#4 /PayPal/lib/PayPal/Handler/RestHandler.php(83): PayPal\Auth\OAuthTokenCredential->getAccessToken(Array)
#5 /PayPal/lib/PayPal/Transport/PayPalRestCall.php(71): PayPal\Handler\RestHandler->handle(Object(PayPal\Core\PayPalHttpConfig), '{"intent":"sale...', Array)
#6 /PayPal/lib/PayPal/Common/PayPalResourceModel.php(102): PayPal\Transport\PayPalRestCall->execute(Array, '/v1/payments/pa...', 'POST', '{"intent":"sale...', NULL)
#7 /PayPal/lib/PayPal/Api/Payment.php(580): PayPal\Common\PayPalResourceModel::executeCall('/v1/payments/pa...', 'POST', '{"intent":"sale...', NULL, Object(PayPal\Rest\ApiContext), NULL)
#8 /test.php(492): PayPal\Api\Payment->create(Object(PayPal\Rest\ApiContext))
#9 {main}
```

**Comment by tekmosis** [comment]
nm found issue for same thing
