### ISSUE TITLE
Fatal error: Call to a member function info() on null

### ISSUE THREAD

**Issue by ChadTaljaardt** [paypal/PayPal-PHP-SDK#559]
Hello, I'm having an issue. 

Here is the error log:

```
[2016-04-21 15:52:39] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to a member function info() on null in /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalLoggingManager.php:95
Stack trace:
#0 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php(76): PayPal\Core\PayPalLoggingManager->info('POST https://ap...')
#1 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(241): PayPal\Core\PayPalHttpConnection->execute('grant_type=clie...')
#2 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(266): PayPal\Auth\OAuthTokenCredential->getToken(Array, 'AYvGjHsTWYoDXie...', 'EB2-QASYt0E67Mo...', 'grant_type=clie...')
#3 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(210): PayPal\Auth\OAuthTokenCredential->generateAccessToken(Array, NULL)
#4 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(160): PayPal\Auth\OAuthTokenCredential->updateAccessToken(Array)
#5 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/paypal/rest-api-sdk-php/lib/PayPal/Handler/RestHandler.php(83): PayPal\Auth\OAuthTokenCredential->getAccessToken(Array)
#6 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php(71): PayPal\Handler\RestHandler->handle(Object(PayPal\Core\PayPalHttpConfig), '{"intent":"sale...', Array)
#7 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php(102): PayPal\Transport\PayPalRestCall->execute(Array, '/v1/payments/pa...', 'POST', '{"intent":"sale...', Array)
#8 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Payment.php(576): PayPal\Common\PayPalResourceModel::executeCall('/v1/payments/pa...', 'POST', '{"intent":"sale...', NULL, Object(PayPal\Rest\ApiContext), Object(PayPal\Transport\PayPalRestCall))
#9 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/amsgames/laravel-shop-gateway-paypal/src/GatewayPayPalExpress.php(116): PayPal\Api\Payment->create(Object(PayPal\Rest\ApiContext))
#10 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/amsgames/laravel-shop/src/LaravelShop.php(164): Amsgames\LaravelShopGatewayPaypal\GatewayPayPalExpress->onCharge(Object(App\Models\Store\Order))
#11 /home/vagrant/Code/Jacqueline-Bell-Jewellery/app/Http/Controllers/Frontend/Store/CheckoutController.php(27): Amsgames\LaravelShop\LaravelShop::placeOrder()
#12 [internal function]: App\Http\Controllers\Frontend\Store\CheckoutController->checkout(Object(Illuminate\Http\Request))
#13 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)
#14 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('checkout', Array)
#15 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Frontend\Store\CheckoutController), Object(Illuminate\Routing\Route), 'checkout')
#16 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Frontend\Store\CheckoutController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'checkout')
#22 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'checkout')
#23 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#24 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /home/vagrant/Code/Jacqueline-Bell-Jewellery/app/Http/Middleware/Authenticate.php(32): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 /home/vagrant/Code/Jacqueline-Bell-Jewellery/app/Http/Middleware/LocaleMiddleware.php(48): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: App\Http\Middleware\LocaleMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#45 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#50 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#55 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#57 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#60 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#62 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#64 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#65 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#66 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#67 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#68 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#69 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#70 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#71 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#73 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#75 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#76 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#77 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#78 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#79 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#80 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#81 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#82 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#83 /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#84 /home/vagrant/Code/Jacqueline-Bell-Jewellery/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#85 {main}  
```

**Comment by ChadTaljaardt** [comment]
I'm trying to checkout a user and it stops here and i can't figure out why?

**Comment by jaypatel512** [comment]
What version of SDK are you using  ?

**Comment by ChadTaljaardt** [comment]
"paypal/rest-api-sdk-php": "*"

**Comment by jaypatel512** [comment]
Did you run `composer update` on your composer file. We have a new added dependency.

**Comment by ChadTaljaardt** [comment]
Yes, it tells me nothing to update.

**Comment by ChadTaljaardt** [comment]
I don't know if it will be any help but i'm using this package to use Paypal https://github.com/amsgames/laravel-shop-gateway-paypal#usage

**Comment by jaypatel512** [comment]
Are you able to reproduce the same error when running samples ? 

You can run `php -f PayPal-PHP-SDK/paypal/rest-api-sdk-php/sample/index.php` to start the samples. They generally should be accessible on localhost:4000. Let me know if you are getting similar error on samples too. This should help us differentiate the issue in your integration vs SDK.

**Comment by ChadTaljaardt** [comment]
Won't connect, i'm using a homestead box, I had to change the code you gave me to 

php -f vendor/paypal/rest-api-sdk-php/sample/index.php

I got this output from the terminal 

vagrant@homestead:~/Code/Jacqueline-Bell-Jewellery$ php -f vendor/paypal/rest-api-sdk-php/sample/index.php
<!-- Welcome to PayPal REST SDK -- >
PHP 7.0.3-13+deb.sury.org~trusty+1 Development Server started at Thu Apr 21 16:56:11 2016
Listening on http://localhost:5000
Document root is /home/vagrant/Code/Jacqueline-Bell-Jewellery/vendor/paypal/rest-api-sdk-php/sample
Press Ctrl-C to quit.

**Comment by ChadTaljaardt** [comment]
Is there anything i can do about this?

**Comment by jaypatel512** [comment]
I would recommend you testing this on local machine. I am trying to find a way to reproduce this issue myself, but I am not able to. 

Please let me know if you can run the samples in your local machine and reproduce the issue.

**Comment by ChadTaljaardt** [comment]
The tests worked

**Comment by ChadTaljaardt** [comment]
I tried a few things like 

https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Core/PayPalLoggingManager.php#L57
returns a empty array

**Comment by jaypatel512** [comment]
Still, it should not return null back there. It should still properly create an instance of Logging Manager for you. 

Can you please add a log statement atleast at https://github.com/paypal/PayPal-PHP-SDK/blob/master/lib/PayPal/Core/PayPalHttpConnection.php#L48 to print $logger object, and confirm if that is not null.

**Comment by ChadTaljaardt** [comment]
PayPalLoggingManager {#476 ▼
  -logger: null
  -loggerName: null
}

**Comment by ChadTaljaardt** [comment]
The logger is null :/

**Comment by jaypatel512** [comment]
Found the bug !! 👍 I have made a new release 1.7.1. Please, update the package, and confirm if that fixes the issue.
