### ISSUE TITLE
Config file not found on sdk

### ISSUE THREAD

**Issue by IgorDePaula** [paypal/PayPal-PHP-SDK#585]
I tried some applications, but on first test, it fails:

I received thie error: 

```
PHP Fatal error:  Uncaught exception 'PPConfigurationException' with message 'Config file /home/igor/projetos/ppal/vendor/paypal/sdk-core-php/lib/../config/sdk_config.ini not found' in /home/igor/projetos/ppal/vendor/paypal/sdk-core-php/lib/PPConfigManager.php:40
Stack trace:
#0 /home/igor/projetos/ppal/vendor/paypal/sdk-core-php/lib/PPConfigManager.php(23): PPConfigManager->load('/home/igor/proj...')
#1 /home/igor/projetos/ppal/vendor/paypal/sdk-core-php/lib/PPConfigManager.php(30): PPConfigManager->__construct()
#2 /home/igor/projetos/ppal/vendor/paypal/sdk-core-php/lib/PPLoggingManager.php(43): PPConfigManager::getInstance()
#3 /home/igor/projetos/ppal/vendor/paypal/rest-api-sdk-php/lib/PayPal/Auth/OAuthTokenCredential.php(49): PPLoggingManager->__construct('PayPal\\Auth\\OAu...')
#4 /home/igor/projetos/ppal/bootstrap.php(62): PayPal\Auth\OAuthTokenCredential->__construct('ARscgNFXYIr2uH6...', 'ELQjkXtYIWHhQbG...')
#5 /home/igor/projetos/ppal/bootstrap.php(35): getApiContext('ARscgNFXYIr2uH6...', 'ELQjkXtYIWHhQbG...')
#6 /h in /home/igor/projetos/ppal/vendor/paypal/sdk-core-php/lib/PPConfigManager.php on line 40

Fatal error: Uncaught exception 'PPConfigurationException' with message 'Config file /home/igor/projetos/ppal/vendor/paypal/sdk-core-php/lib/../config/sdk_config.ini not found' in /home/igor/projetos/ppal/vendor/paypal/sdk-core-php/lib/PPConfigManager.php on line 40

PPConfigurationException: Config file /home/igor/projetos/ppal/vendor/paypal/sdk-core-php/lib/../config/sdk_config.ini not found in /home/igor/projetos/ppal/vendor/paypal/sdk-core-php/lib/PPConfigManager.php on line 40
```
I used this code: https://github.com/paypal/PayPal-PHP-SDK/wiki/Making-First-Call
I used the common and bootstrap files from sample folder.
I only copy the code, change for my client id and secret.
- PHP Version: 5.6
- PayPal-PHP-SDK Version: 0.5.0
- Debug ID(s): ??

**Comment by jaypatel512** [comment]
You are using the wrong project. We have moved away from sdk-core-php dependency long back. Please make sure you are using the latest version of PayPal-PHP-SDK version: https://github.com/paypal/PayPal-PHP-SDK/releases/tag/1.7.2
