### ISSUE TITLE
CRITICAL Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment

### ISSUE THREAD

**Issue by SteaveAshmore** [paypal/PayPal-PHP-SDK#754]
### Required Information

- PHP Version: 5.6
- PayPal-PHP-SDK Version: latest
- Debug ID(s):

### Issue Description
Facing same and unable to handle exeption
CRITICAL - Uncaught PHP Exception PayPal\Exception\PayPalConnectionException: "Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment." at C:\wamp\www\taxi\vendor\paypal\rest-api-sdk-php\lib\PayPal\Core\PayPalHttpConnection.php line 154

**Comment by jaypatel512** [comment]
Can you please catch proper exception to get detailed information about the error. You can achieve that by following the sample shown here: https://github.com/paypal/PayPal-PHP-SDK/wiki/exception-%27PayPal%5CException%5CPayPalConnectionException%27-with-message-%27Got-Http-response-code-400-when-accessing

**Comment by jlahijani** [comment]
I think I'm experiencing the same issue as well.  My error output (note: I'm using ProcessWire CMS although I don't think that makes a difference):

```

400{"name":"UNAUTHORIZED_PAYMENT","message":"Unauthorized payment","information_link":"https://developer.paypal.com/docs/api/#UNAUTHORIZED_PAYMENT","debug_id":"90d7cf2a9d1a1"}PayPal\Exception\PayPalConnectionException: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment/PAY-2H55266608020935TLBXOG6Y. in /mnt/c/Users/jlahijani/Projects/test-site/vendor/paypal/rest-api-sdk-php/lib/PayPal/Core/PayPalHttpConnection.php:178
Stack trace:
#0 /mnt/c/Users/jlahijani/Projects/test-site/vendor/paypal/rest-api-sdk-php/lib/PayPal/Transport/PayPalRestCall.php(74): PayPal\Core\PayPalHttpConnection->execute('')
#1 /mnt/c/Users/jlahijani/Projects/test-site/vendor/paypal/rest-api-sdk-php/lib/PayPal/Common/PayPalResourceModel.php(102): PayPal\Transport\PayPalRestCall->execute(Array, '/v1/payments/pa...', 'GET', '', Array)
#2 /mnt/c/Users/jlahijani/Projects/test-site/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Payment.php(600): PayPal\Common\PayPalResourceModel::executeCall('/v1/payments/pa...', 'GET', '', NULL, Object(PayPal\Rest\ApiContext), Object(PayPal\Transport\PayPalRestCall))
#3 /mnt/c/Users/jlahijani/Projects/test-site/site/templates/paypal-api-execute-payment.php(31): PayPal\Api\Payment::get('PAY-2H552666080...', Object(PayPal\Rest\ApiContext))
#4 /mnt/c/Users/jlahijani/Projects/test-site/wire/core/TemplateFile.php(268): require('/mnt/c/Users/jl...')
#5 /mnt/c/Users/jlahijani/Projects/test-site/wire/core/Wire.php(374): ProcessWire\TemplateFile->___render()
#6 /mnt/c/Users/jlahijani/Projects/test-site/wire/core/WireHooks.php(698): ProcessWire\Wire->_callMethod('___render', Array)
#7 /mnt/c/Users/jlahijani/Projects/test-site/wire/core/Wire.php(402): ProcessWire\WireHooks->runHooks(Object(ProcessWire\TemplateFile), 'render', Array)
#8 /mnt/c/Users/jlahijani/Projects/test-site/wire/modules/PageRender.module(514): ProcessWire\Wire->__call('render', Array)
#9 [internal function]: ProcessWire\PageRender->___renderPage(Object(ProcessWire\HookEvent))
#10 /mnt/c/Users/jlahijani/Projects/test-site/wire/core/Wire.php(376): call_user_func_array(Array, Array)
#11 /mnt/c/Users/jlahijani/Projects/test-site/wire/core/WireHooks.php(698): ProcessWire\Wire->_callMethod('___renderPage', Array)
#12 /mnt/c/Users/jlahijani/Projects/test-site/wire/core/Wire.php(402): ProcessWire\WireHooks->runHooks(Object(ProcessWire\PageRender), 'renderPage', Array)
#13 /mnt/c/Users/jlahijani/Projects/test-site/wire/core/WireHooks.php(782): ProcessWire\Wire->__call('renderPage', Array)
#14 /mnt/c/Users/jlahijani/Projects/test-site/wire/core/Wire.php(402): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Page), 'render', Array)
#15 /mnt/c/Users/jlahijani/Projects/test-site/wire/modules/Process/ProcessPageView.module(205): ProcessWire\Wire->__call('render', Array)
#16 [internal function]: ProcessWire\ProcessPageView->___execute(true)
#17 /mnt/c/Users/jlahijani/Projects/test-site/wire/core/Wire.php(376): call_user_func_array(Array, Array)
#18 /mnt/c/Users/jlahijani/Projects/test-site/wire/core/WireHooks.php(698): ProcessWire\Wire->_callMethod('___execute', Array)
#19 /mnt/c/Users/jlahijani/Projects/test-site/wire/core/Wire.php(402): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessPageView), 'execute', Array)
#20 /mnt/c/Users/jlahijani/Projects/test-site/index.php(62): ProcessWire\Wire->__call('execute', Array)
#21 {main}
```

**Comment by jlahijani** [comment]
To be more specific, it's being caused by this line when I get to the execute payment step in my checkout flow:
```
$payment = Payment::get($_GET['paymentId'], $apiContext);
```

**Comment by bluk** [comment]
@jlahijani In your [account status](https://developer.paypal.com/developer/accountStatus/), can you check to ensure `PayPal payments` is enabled?

**Comment by jlahijani** [comment]
@bluk Yes it's enabled.

**Comment by jlahijani** [comment]
@bluk Nevermind.  I realized I had a variable named incorrectly (the variable that holds the App Secret).  As a result, the error that PayPal throws is Unauthorized Payment, which is really weird.  This took me many hours to figure out, but it's my fault.  FML.

**Comment by bluk** [comment]
@jlahijani I'm glad you were able to fix your issue.
